### ISSUE TITLE
Buildkite agent installation requires GUI login

### ISSUE THREAD

**Issue by bachand** [buildkite/homebrew-buildkite#22]
After installing the buildkite Homebrew package, the [instructions](https://buildkite.com/docs/agent/v3/macos#starting-on-login) indicate that you should run `brew info buildkite-agent` to determine how to install the service at login.

The instructions from running `brew info buildkite-agent` indicate that it's necessary to enable auto-login on your Mac.
![Screen Shot 2022-02-16 at 10 33 45 AM](https://user-images.githubusercontent.com/1791049/155447353-0550048a-33f8-4cbb-820d-11fed4d01913.png)

Buildkite's [instructions](https://buildkite.com/docs/agent/v3/elastic-ci-stack-for-ec2-mac/autoscaling-mac-metal#step-2-build-an-ami) for creating an AMI indicate the same.

![Screen Shot 2022-02-23 at 6 42 27 PM](https://user-images.githubusercontent.com/1791049/155447474-2cb347e1-458a-4ce2-8e7e-553b9c80955e.png)

I am trying to create a macOS AMI using Packer ([tutorial](https://aws.amazon.com/blogs/compute/building-amazon-machine-images-amis-for-ec2-mac-instances-with-packer/)). The AMI creation process will be smoother and more flexible if we can remove the manual steps of VNC'ing into instances.

The recommended way to install the Buildkite agent is to run `brew services start buildkite/buildkite/buildkite-agent`. This command fails when run as part of Packer.
![Screen_Shot_2022-02-16_at_1_11_34_PM](https://user-images.githubusercontent.com/1791049/155448526-cf393f70-3cd0-47c7-bbdd-3409a7542885.png)

`launchctl` provides a way to create launch daemons that appear not to require a GUI login. I am not sure what is allowed at the Homebrew level.

![Screen Shot 2022-02-22 at 2 59 57 PM](https://user-images.githubusercontent.com/1791049/155448132-01407942-5e99-441f-92de-2c1537231ac3.png)

My request in this issue is for Buildkite to create a "blessed" path for installing a buildkite agent launch daemon without a GUI login.

I can devise ways to start the Buildkite agent in the background without a launch agent but there are two downsides: (1) the instance will not be usable if the Buildkite agent were to crash and (2) my own method for installing the Builkdkite agent will not automatically inherit changes to the installation process that may be made by Buildkite in the future.

**Comment by DrJosh9000** [comment]
Hi @bachand, thanks for raising the issue (back in Feb! A collective "sorry" for the delay in responding). 

I'm new enough at Buildkite that I don't have the context for the choice to recommend LaunchAgents over LaunchDaemons or what was written in the README, but it sounds plausible. I don't really see why we wouldn't be able to "bless" running the agent as a LaunchDaemon, but I will keep investigating before making such a promise.

That said:

- I did some experimenting with running the agent as a LaunchDaemon rather than LaunchAgent (`sudo brew services start...` as opposed to `brew services start...`). It seems to work fine for building a simple pipeline (testing a small Go library).
- LaunchDaemons run as root, so any security issues could potentially become more spicy (e.g. someone sneaks some malicious code into a repository that gets run under the agent - now as root). But this might not be a blocking issue for a variety of reasons (e.g. if you don't care so much about mass-provisioned cloud instances, or the hypothetical existence of local privilege escalation vulnerabilites in macOS which would make moot the distinction between root and non-root).

**Comment by sj26** [comment]
Hi @bachand, we're going to close this but please reopen if you still have issues.
